# Generated by Django 3.2.6 on 2023-02-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230224_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\User\\Desktop\\Домашка\\coursework_6_skymarket\\skymarket\\django_media'),
        ),
    ]
